# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
    initrd.kernelModules = [  ];
    kernelModules = [ "kvm-intel" "sc0710"];
    extraModulePackages = [ ];
    loader.grub = {
      efiSupport = true;
      device = "nodev";
      useOSProber = true;
      default = "saved";
      configurationLimit = 3;
    };
    loader.grub2-theme = {
      enable = true;
      theme = "stylish";
      footer = true;
      splashImage = ./assets/background-stylish2.jpg;
      customResolution = "3840x2160";  # Optional: Set a custom resolution
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f7d90429-9439-4053-91b3-e6b2193d4459";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D742-7346";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2e9d52d8-5d02-43f1-b58f-27b5396ccc88"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u11u3.useDHCP = lib.mkDefault true;

  fileSystems."/media/romdisk" = {
    device = "/dev/disk/by-uuid/FAD696A1D6965E27";
    fsType = "ntfs";
    options = [ "uid=1000" "gid=100" "dmask=022" "fmask=133" ];
  };

  fileSystems."/media/mediadisk" = {
    device = "/dev/disk/by-uuid/4C58849358847E08";
    fsType = "ntfs";
    options = [ "uid=1000" "gid=100" "dmask=022" "fmask=133" ];
  };


  hardware.xone.enable = true;
  hardware.xpadneo.enable = true;
  boot.extraModprobeConfig = ''
    options bluetooth disable_ertm=1
  '';
  nixpkgs.config.allowUnfree = true;

  hardware.enableAllFirmware = true;

	hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;
  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.nvidiaPersistenced = true;

  services.xserver.videoDrivers = [ "nvidia" ];
  
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;
  hardware.nvidia.open = false;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}