# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
    initrd.kernelModules = [ "ntsync" "sg" ];
    kernelModules = [ "kvm-intel" ];
    consoleLogLevel = 3;
    
    extraModulePackages = [ config.boot.kernelPackages.nvidiaPackages.legacy_580 ];
    
    loader.grub = {
      efiSupport = true;
      device = "nodev";
      useOSProber = true;
      default = "saved";
      configurationLimit = 3;
      timeout = 0;
    };
    loader.grub2-theme = {
      enable = true;
      theme = "stylish";
      footer = true;
      splashImage = ./assets/background-stylish.jpg;
      customResolution = "1920x1080";  # Optional: Set a custom resolution
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d9807655-133d-44f3-b478-8bd8677ee098";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2C26-57DF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/data_disk" = {
    device = "/dev/disk/by-uuid/417a46a4-b863-4b84-8399-4fb1aa770c3a";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/da633cab-426d-4ef5-9479-2e1844b143c1"; }
    ];


    services.udev.extraRules = ''
      KERNEL=="sr0", GROUP="optical", MODE="0660"
      KERNEL=="sg*", GROUP="optical", MODE="0660"
    '';

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u11u3.useDHCP = lib.mkDefault true;networking.networkmanager.enable = true;
  networking.networkmanager.enable = true;
  networking.interfaces.wlp0s20f3.useDHCP = true;

  hardware.xone.enable = true;
  hardware.xpadneo.enable = true;
  boot.extraModprobeConfig = ''
    options bluetooth disable_ertm=1
  '';
  boot.supportedFilesystems = [ "ntfs" ];
  nixpkgs.config.allowUnfree = true;

  hardware.enableAllFirmware = true;

  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_580;
  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.nvidiaPersistenced = true;

  services.xserver.videoDrivers = [ "nvidia" ];
  
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;
  hardware.nvidia.open = false;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  hardware.nvidia = {
    powerManagement.enable = true;
    powerManagement.finegrained = false; # keep this off on Pascal
  };
  
  hardware.nvidia.prime = {
    sync.enable = true; # or offload mode
    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:1:0:0";
  };
}
